// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import FormSubmitController from "./form_submit_controller"
application.register("form-submit", FormSubmitController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import QuestionController from "./question_controller"
application.register("question", QuestionController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import TimeSavedController from "./time_saved_controller"
application.register("time-saved", TimeSavedController)
